version: "2"
services:
  server:
    container_name: home-server
    #restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://mongo:27017/home
      - PORT=8080
      - TZ=America/Argentina/Buenos_Aires
  db:
    container_name: mongo
    image: mongo:latest
    volumes:
      - /Users/sebastian.etchevest/documents/code/home-station/home-data-server/data:/data/db
    ports:
      - "27017:27017"